name: loyalty_points
description: "A loyalty program, where points can be collected with every purchase
  products."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # * state management
  get: ^4.7.2

  # * For multi languages
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_localized_locales: ^2.0.5

  # * To make == operator
  equatable: ^2.0.7

  # * For preview to show in responsive design
  device_preview: ^1.2.0

  # * local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1

  local_auth: ^2.3.0

  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1

  # * To make mobile field
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop 

  # * for pick or take image
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.7
  permission_handler: ^12.0.0+1
  
  # * for loading
  skeletonizer: ^1.4.3
  
  # * for easy ui
  dotted_border: ^2.1.0
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  flutter_typeahead: ^5.2.0

  # * for firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.1.0
 
  
  # * Helper packages
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  #* for native splash screen
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  arb_dir: assets/languages
  output_dir: lib/core/utils/config/locale/generated
