name: Build APK & AAB on 'make new app' commit

on:
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, 'make new app')
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v3

      - name: â˜• Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: ğŸ¦ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: ğŸ“¦ Install dependencies
        run: flutter pub get
      
      - name: ğŸ·ï¸ Extract version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | cut -d' ' -f2 | tr -d '\r')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: ğŸ” Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks

      - name: ğŸ“ Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: ğŸ› ï¸ Build APKs (split per ABI)
        run: flutter build apk --release --split-per-abi

      - name: ğŸ“¦ Build App Bundle (AAB)
        run: flutter build appbundle --release

      # - name: ğŸ“¦ Build Web 
      #   run: |
      #       flutter build web --web-renderer html --release 
      #       cd build/web
      #       find . -type d -exec chmod 777 {} \;
      #       sudo chmod -R 666 .
      #       sudo find . -type d -exec chmod 777 {} \;
      #       sudo find . -type f -exec chmod 666 {} \;

      - name: ğŸ“¤ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.version.outputs.VERSION }}(APK)
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: ğŸ“¤ Upload App Bundle (AAB)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.version.outputs.VERSION }}(AAB)
          path: build/app/outputs/bundle/release/app-release.aab

      # - name: ğŸ“¤ Upload Website
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ github.event.repository.name }}-${{ steps.version.outputs.VERSION }}-Website
      #     path: build/web/*

      - name: ğŸ“¤ Upload Symbols
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.version.outputs.VERSION }}-symbols
          path: build/app/intermediates/merged_native_libs/release/out/lib/*